### ISSUE TITLE
Handling Sender exceptions

### ISSUE THREAD

**Issue by jaymell** [reactor/reactor-rabbitmq#86] opened 2019-04-13 06:54 UTC
I have a very simple Spring Boot application, based on your sample Spring boot program, publishing messages to rabbitmq. I'm having a difficult time grokking how to properly surface and handle certain exceptions. For example, if the exchange I'm trying to publish to doesn't exist, the following code will never return.

This is the exception thrown on rabbitmq's side
```
operation basic.publish caused a channel exception not_found: no exchange 'myexchange' in vhost '/'
```

Can someone provide insight into whether this is expected behavior?

This is the code:
```
@Configuration
class RabbitConfig {

    @Value("\${rabbitmq.exchange}")
    lateinit var exchangeVar: String

    @Bean
    fun exchange(): String = exchangeVar

    @Bean
    fun connectionMono(connectionFactory: ConnectionFactory): Mono<Connection?> =
            Mono.fromCallable { connectionFactory.createConnection().delegate }

    @Bean
    fun sender(connectionMono: Mono<Connection>): Sender = RabbitFlux.createSender(SenderOptions().connectionMono(connectionMono))
}


class ObjController {
    companion object : KLogging()

    @Autowired
    lateinit var sender: Sender

    @Autowired
    lateinit var exchange: String

    val mapper = jacksonObjectMapper()
    @PostMapping
    fun postObj(@RequestBody Objs: List<Obj>): Mono<ResponseEntity<HttpStatus>> {

        val objFlux = Objs.toFlux()
                .map { obj: Obj ->
                    OutboundMessage(exchange,
                            obj.id,
                            AMQP.BasicProperties().builder().priority(obj.priority).build(),
                            mapper.writeValueAsBytes(obj))
                }

        val sendOptions = SendOptions()
                .exceptionHandler(ExceptionHandlers.RetrySendingExceptionHandler(
                        Duration.ofSeconds(1),
                        Duration.ofMillis(500),
                        ExceptionHandlers.CONNECTION_RECOVERY_PREDICATE))

        return sender.sendWithPublishConfirms(objFlux, sendOptions).
                .then(Mono.just(ResponseEntity<HttpStatus>(HttpStatus.ACCEPTED)))
                .onErrorResume(AmqpConnectException::class) {
                    logger.error("Failed to connect to rabbitmq")
                    Mono.just(ResponseEntity<HttpStatus>(HttpStatus.valueOf(500)))
                }
                .onErrorResume(Exception::class) { e: Exception ->
                    logger.error("Unknown exception", e)
                    Mono.just(ResponseEntity<HttpStatus>(HttpStatus.valueOf(500)))
                }
```

I have a similar problem if rabbitmq goes completely down on the receiving side. I appreciate any insights anyone can provide.

**Comment by acogoluegnes** [comment] 2019-04-15 08:08
Sending is asynchronous in AMQP, so if the target exchange does not exist, the server will close the channel, but the client can move on to any other operation in the meantime (between the end of the sending and the server-initiated channel closing).

In your case, you need to make sure the exchange exists before sending anything to it. I added a test as an example: 110bec135ff569cfd91de80f6d2431d0b9a52aac.

It's also possible to "passive" declare, but this is not implemented yet in Reactor RabbitMQ, #84 will fix this soon.

Regarding the issue on the receiving, Reactor RabbitMQ supports connection recovery, so a consumer should resume when the server comes back up. Can you please more specific about the problem? (steps to reproduce, server version and log, client version and log).

**Comment by jaymell** [comment] 2019-04-15 18:37
Thanks for the comment. I will definitely see about ensuring the exchange exists before creating, but I'm confused as to why no exception is surfaced either on the Connection publisher, the Sender, or within the `sendWithPublishConfirms` flux. 

I'd like to be able to handle the failure a little more gracefully if, say, the exchange gets deleted for some reason.

On the receiving side, the code is again very simple:
```
@Configuration
class RabbitConfig {

    @Value("\${rabbitmq.queue}")
    lateinit var queue: String

    @Bean
    fun connectionMono(connectionFactory: ConnectionFactory): Mono<Connection?> =
            Mono.fromCallable { connectionFactory.createConnection().delegate }
                    .onErrorResume { throw Exception("connection Exception") }

    @Bean
    fun sender(connectionMono: Mono<Connection>): Sender = RabbitFlux.createSender(SenderOptions().connectionMono(connectionMono)
            .channelCloseHandler { t, u -> println("channel closed: $t"); throw Exception("sender exception") })

    @Bean
    fun receiver(connectionMono: Mono<Connection>): Receiver = RabbitFlux.createReceiver(ReceiverOptions().connectionMono(connectionMono))

    @Bean
    fun deliveryFlux(receiver: Receiver): Flux<AcknowledgableDelivery> = receiver.consumeManualAck(queue)
}


@Component
class Runner @Autowired constructor(val deliveryFlux: Flux<AcknowledgableDelivery>, val sender: Sender) : CommandLineRunner {
    companion object : KLogging()

    val mapper = jacksonObjectMapper()

    override fun run(vararg args: String) {
        logger.info("Application started.")

        deliveryFlux.map {
            logger.debug("Received message from queue: ${mapper.readValue<Obj>(it.body)}")
            it
        }
                .map {
                    it.ack()
                }
                .subscribe()
    }

```

If I restart rabbitmq while this process is running, I don't see any recovery after it's restarted -- i.e., I have to restart the application in order to continue processing messages.

This is with rabbitmq 3.7.14
reactor-rabbitmq version 1.2.0.RELEASE
spring-amqp version 2.1.5.RELEASE

Thanks again for your help.

**Comment by acogoluegnes** [comment] 2019-04-17 06:46
Have you changed the logging level? Not sure if such errors are logged at the ERROR level.

For the publishing side, there may be no error because the sending is asynchronous, so the sending sequence (publishing to a non-existing exchange, closing the channel) completes before the server initiates the closing of the channel.

Regarding the consuming side, it's hard to diagnose without logs or steps to reproduce. Can you provide a sample project and steps to reproduce?

Thanks.

**Comment by acogoluegnes** [comment] 2019-04-17 13:30
OK, found the problem with the re-connection. Spring Boot uses Spring AMQP, which disables automatic connection recovery at the Java client level, to use its own connection recovery mechanism. Connection recovery in Reactor RabbitMQ is based on the Java client mechanism, this is why it doesn't work in your case.

You can change the `connectionMono` declaration to the following to fix the problem:

```java
@Bean
Mono<Connection> connectionMono(CachingConnectionFactory connectionFactory) {
  ConnectionFactory rabbitConnectionFactory = connectionFactory.getRabbitConnectionFactory();
  rabbitConnectionFactory.setAutomaticRecoveryEnabled(true);
  rabbitConnectionFactory.setTopologyRecoveryEnabled(true);
  return Mono.fromCallable(() -> rabbitConnectionFactory.newConnection()).cache();
}
```

However, I'm not 100% satisfied with this solution because it kinda breaks Spring AMQP for the application, so this works well if you don't use Spring AMQP in the Spring Boot application (no listeners, etc). I'll create an issue to find a better solution and fix the Spring Boot sample.

**Comment by jaymell** [comment] 2019-04-18 03:50
Thanks for the info about receiving. With the modified connection bean, it is now reestablishing the connection properly after rabbitmq is restarted, so this will definitely work for me at this point.

Regarding the sender side, I noticed that I posted some incorrect code in my initial post -- I'm actually trying to use `sendWithPublishConfirms` -- if I use just `send`, the code will return succesfully (though obviously I end up passing a 202 rather than a 500). With `sendWithPublishConfirms`, however, the function just hangs indefinitely. I've got full debug logging turned on but am not seeing any meaningful responses.

**Comment by acogoluegnes** [comment] 2019-04-18 07:03
The problem you mention with `sendWithPublishConfirms` occurs when the exchange you publish to does not exist, right?

**Comment by jaymell** [comment] 2019-04-22 16:13
That's correct. The sender just seems to sit there blocked when the exchange doesn't exist.

I understand that the server closes the connection, but I'm confused as to why I don't see the connection closure in the application logging. My sender bean looks like this:

```
    @Bean
    fun sender(connectionMono: Mono<Connection>): Sender = RabbitFlux.createSender(SenderOptions().connectionMono(connectionMono)
            .channelCloseHandler { t, u -> logger.error("Channel closed") })
```

But the only time I see the channel close handler get called is when I hit Ctrl+C on the blocked `curl` invocation I run for testing. It does not get called in the actual process of attempting to send the message.

**Comment by acogoluegnes** [comment] 2019-04-23 06:52
The channel close handler is meant to be called by the client internally, when it's done with the channel. It was introduced to optionally add channel pooling. So it's normal it's not called when the server initiated the channel closing.

In your case, the reactive flow is just hanging, waiting for publisher confirms to come. They will never come as the channel has been closed. One way to mitigate this would be to time out if nothing shows up in the flux. I don't know if this is possible with Reactor.

This is an awkward situation though, I'll see if there's something we can do to get at least notified that the channel has been closed.

**Comment by acogoluegnes** [comment] 2019-04-23 07:14
A channel shutdown listener is notified when the channel is closed by the server, so it's a good place to emit an error to the flux. I'll work on a fix.

**Closed** 2019-06-17 11:40 UTC
Labels: effort-low, usability
